DELETE FROM trackers.transportation;
ALTER TABLE trackers.transportation AUTO_INCREMENT = 1;
INSERT INTO trackers.transportation (id, transport) VALUES (null, 'Horse');
INSERT INTO trackers.transportation (id, transport) VALUES (null, 'Car');
INSERT INTO trackers.transportation (id, transport) VALUES (null, 'Bus');
INSERT INTO trackers.transportation (id, transport) VALUES (null, 'Bicycle');
INSERT INTO trackers.transportation (id, transport) VALUES (null, 'Motorcycle');
INSERT INTO trackers.transportation (id, transport) VALUES (null, 'Skates');
INSERT INTO trackers.transportation (id, transport) VALUES (null, 'Ski');
INSERT INTO trackers.transportation (id, transport) VALUES (null, 'Hang gliding');
INSERT INTO trackers.transportation (id, transport) VALUES (null, 'Tandem');